"""Agregar columna precio_soles a Producto

Revision ID: 1117ccf61f6c
Revises: dac87f5435e2
Create Date: 2025-02-27 11:11:13.791987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1117ccf61f6c'
down_revision = 'dac87f5435e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('precio_soles', sa.Numeric(precision=10, scale=2), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.drop_column('precio_soles')

    # ### end Alembic commands ###
