"""Agregar columnas a Producto

Revision ID: 1669f30f6e5b
Revises: 
Create Date: 2025-02-26 12:54:19.666309

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1669f30f6e5b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('codigo', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('descripcion', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('stock', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('precio_dolares', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('garantia', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('marca', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('categoria', sa.String(length=100), nullable=False))
        batch_op.drop_column('precio')
        batch_op.drop_column('cantidad')
        batch_op.drop_column('nombre')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('cantidad', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('precio', mysql.DECIMAL(precision=10, scale=2), nullable=False))
        batch_op.drop_column('categoria')
        batch_op.drop_column('marca')
        batch_op.drop_column('garantia')
        batch_op.drop_column('precio_dolares')
        batch_op.drop_column('stock')
        batch_op.drop_column('descripcion')
        batch_op.drop_column('codigo')

    # ### end Alembic commands ###
