"""Modifica almacen_id a String

Revision ID: dac87f5435e2
Revises: 1669f30f6e5b
Create Date: 2025-02-26 15:22:36.912571

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dac87f5435e2'
down_revision = '1669f30f6e5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('almacen', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=100),
               existing_nullable=False)

    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.alter_column('almacen_id',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'almacen', ['almacen_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('almacen_id',
               existing_type=sa.String(length=100),
               type_=mysql.INTEGER(),
               existing_nullable=True)

    with op.batch_alter_table('almacen', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.String(length=100),
               type_=mysql.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
